defmodule FindIt.Inventory.Item do
  use Ash.Resource,
    otp_app: :find_it,
    domain: FindIt.Inventory,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshGraphql.Resource]

  graphql do
    type :item

    queries do
      list :list_items, :read
      get :get_item, :read
    end

    mutations do
      create :create_item, :create
      update :update_item_status, :update_status
    end
  end

  postgres do
    table "items"
    repo FindIt.Repo

    references do
      reference :category, on_delete: :restrict
      reference :location, on_delete: :restrict
    end
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      accept [:description, :image_url, :found_at, :category_id, :location_id]

      change fn changeset, _ ->
        count =
          FindIt.Repo.aggregate(FindIt.Inventory.Item, :count, :id)

        code = "OBJ-#{String.pad_leading(to_string(count + 1), 3, "0")}"
        Ash.Changeset.force_change_attribute(changeset, :code, code)
      end
    end

    update :update_status do
      accept [:status]
    end

    update :mark_ai_processed do
      accept [:description, :ai_tags]
      change set_attribute(:ai_processed, true)
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :code, :string do
      allow_nil? false
      public? true
      writable? false
      description "Auto-generated code, e.g. OBJ-001"
    end

    attribute :description, :string do
      public? true
      description "AI-generated or manually entered description"
    end

    attribute :image_url, :string do
      public? true
      description "Path to the photo captured by ESP32-CAM"
    end

    attribute :ai_tags, {:array, :string} do
      public? true
      default []
      description "Tags generated by the AI pipeline"
    end

    attribute :ai_processed, :boolean do
      public? true
      default false
      writable? false
    end

    attribute :status, FindIt.Inventory.ItemStatus do
      public? true
      default :available
    end

    attribute :found_at, :date do
      public? true
      description "Date the item was found on campus"
    end

    create_timestamp :created_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :category, FindIt.Catalog.Category do
      public? true
      domain FindIt.Catalog
    end

    belongs_to :location, FindIt.Catalog.Location do
      public? true
      domain FindIt.Catalog
    end
  end

  identities do
    identity :unique_code, [:code]
  end
end
