defmodule FindIt.Repo.Migrations.AddItemResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:locations), :inserted_at, to: :created_at

    create table(:items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :description, :text
      add :image_url, :text
      add :ai_tags, {:array, :text}, default: []
      add :ai_processed, :boolean, default: false
      add :status, :text, default: "available"
      add :found_at, :date

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :category_id,
          references(:categories,
            column: :id,
            name: "items_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :location_id,
          references(:locations,
            column: :id,
            name: "items_location_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:items, [:code], name: "items_unique_code_index")

    rename table(:categories), :inserted_at, to: :created_at
  end

  def down do
    rename table(:categories), :created_at, to: :inserted_at

    drop constraint(:items, "items_category_id_fkey")

    drop constraint(:items, "items_location_id_fkey")

    drop_if_exists unique_index(:items, [:code], name: "items_unique_code_index")

    drop table(:items)

    rename table(:locations), :created_at, to: :inserted_at
  end
end
