defmodule FindIt.Repo.Migrations.AddSetorToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :setor, :text
    end
  end

  def down do
    alter table(:users) do
      remove :setor
    end
  end
end
