defmodule FindIt.Repo.Migrations.AddPickupResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pickups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :student_name, :text, null: false
      add :student_ra, :text, null: false
      add :student_cpf, :text, null: false
      add :retrieved_at, :date, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "pickups_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false
    end
  end

  def down do
    drop constraint(:pickups, "pickups_item_id_fkey")

    drop table(:pickups)
  end
end
